env: local
allowed_origins:
  - "localhost:3030"
postgres:
  url:
  port: 5432
server:
  addr: localhost:3000
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s
redis:
  url:
  read_timeout: 10s
  write_timeout: 10s
  dial_timeout: 10s
  shutdown_time: 5s
access:
  expiration: 5m
refresh:
  expiration: 15m
rabbitmq:
  queue_name: EMAILS
