env: local
schedule: "* * * * *"
postgres:
  user: postgres
  password: postgres
  database: exhort
  host: localhost
  port: 5432
rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest
  queue_name: EMAILS
